services:
  gateway:
    build: ./api-gateway
    ports:
      - "${GATEWAY_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth-service
      - chat-service

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - sql-server
      - rabbitmq

  chat-service:
    build: ./chat-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

volumes:
  mongo-data: