services:
  gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth-service
      - chat-service

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - sql-server
      - rabbitmq

  chat-service:
    build: ./chat-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
