services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Strong@Passw0rd

  rabbitmq:
    image: rabbitmq:4.1-management
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Strong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  chat-service:
    build: ./chat-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb://admin:Strong@Passw0rd@mongo:27017/chatdb?authSource=admin
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - SQL_SERVER_HOST=sql-server
      - SQL_SERVER_PORT=1433
      - SQL_SERVER_USERNAME=sa
      - SQL_SERVER_PASSWORD=Strong@Passw0rd
      - SQL_SERVER_DATABASE=authdb
    depends_on:
      - sql-server

  gateway:
    build: ./api-gateway
    depends_on:
      - rabbitmq
      - chat-service
      - auth-service
    ports:
      - "3000:3000"
